name: 'latex-typeset-action'
description: 'A GitHub action for typesetting latex projects'
inputs:
  filename:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: "/entrypoint.sh"
  args:
    - ${{ inputs.filename }}