name: 'latex-typeset-action'
description: 'A GitHub action for typesetting latex projects'
inputs:
  filename:
    required: true
runs:
  using: 'docker'
  image: 'ssinad/latex-ubuntu-image:2.11.1.1'
  entrypoint: 'entrypoint.sh'
  args:
    - ${{ inputs.filename }}